tags:
  - name: admin/auth
    description: Authentication APIs for admin

paths:
  /api/v1/admin/auth:
    get:
      summary: Logged In
      tags: [admin/auth]
      responses:
        200:
          description: Returns logged in user
    post:
      summary: Login
      tags: [admin/auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: email
                  example: shahan.khaan@gmail.com
                password:
                  type: string
                  description: password
                  example: 123Abc456
      responses:
        200:
          description: Returns user's payload along with tokens

  /api/v1/admin/auth/refresh/{token}:
    get:
      summary: Refresh Token
      tags: [admin/auth]
      parameters:
        - in: path
          name: token
          schema:
            type: string
          required: true
          description: refresh token string to get new access and refresh token
      responses:
        200:
          description: Returns user's payload along with tokens